# Auto-generated job descriptions for common IT roles

JOB_DESCRIPTION_SAMPLES = {
    "Software Developer": (
        "A Software Developer is responsible for the full software development lifecycle, including requirements gathering, technical design, coding, testing, deployment, and ongoing maintenance of software applications and systems. This role involves participating in code reviews, debugging and resolving technical issues, and writing maintainable, well-documented code in languages such as Java, C++, Python, or JavaScript. Developers collaborate with UI/UX designers, backend engineers, QA testers, and product managers to ensure software quality and alignment with user needs. Typical duties include unit testing, performance optimization, integrating third-party APIs, adopting version control best practices, leveraging Agile or Scrum methodologies, and mentoring junior team members. Additional tasks may involve continuous integration/deployment (CI/CD), documentation, and proactive adoption of new technologies."
    ),
    "Cybersecurity Analyst": (
        "A Cybersecurity Analyst safeguards an organization's digital assets by monitoring network activity, conducting vulnerability scans, and analyzing system logs and alerts. Responsibilities include configuring and managing security tools (firewalls, intrusion detection/prevention systems), applying patches, developing and enforcing security protocols, and coordinating incident response. The role requires conducting risk assessments, forensic analysis, detailed reporting of incidents, and collaborating with IT and compliance teams to meet regulatory requirements. Cybersecurity Analysts also perform penetration testing, simulate attack scenarios, and recommend infrastructure and application security improvements while keeping up-to-date with the latest threat landscape."
    ),
    "Data Scientist": (
        "A Data Scientist analyzes and interprets large volumes of data to provide actionable insights and drive business decisions. Primary duties include designing statistical analyses, building and validating machine learning models, and using programming languages like Python and R with libraries such as Pandas, NumPy, Scikit-learn, TensorFlow, or PyTorch. Data scientists collect, clean, and preprocess data from multiple sources, create visualizations and dashboards, and clearly communicate findings to stakeholders. They work closely with data engineers and business teams to implement data-driven solutions, deploy predictive models, conduct A/B testing, and document methodologies using advanced analytics and big data technologies."
    ),
    "Network Administrator": (
        "A Network Administrator configures, manages, and troubleshoots computer networks—including LANs, WANs, VPNs, and cloud-based infrastructure. Typical responsibilities include installing and upgrading network hardware and software, monitoring network performance, managing user permissions, and enforcing security protocols. They respond to connectivity issues, maintain network documentation, and handle network maintenance to reduce downtime. The role may involve managing remote access, wireless networks, disaster recovery, and compliance with IT policies, as well as collaborating with IT support and vendors."
    ),
    "Cloud Engineer": (
        "A Cloud Engineer designs, deploys, and manages cloud infrastructure and services using platforms like AWS, Azure, or Google Cloud. Key responsibilities include architecting scalable and secure cloud solutions, automating deployments with Infrastructure as Code (Terraform or CloudFormation), and integrating monitoring and logging. Cloud Engineers implement backup and disaster recovery strategies, optimize costs, build CI/CD pipelines, and support containerization (Docker, Kubernetes). They advise on cloud migration and modernization, ensure compliance with security standards, troubleshoot deployment issues, and regularly educate teams on cloud-native practices."
    ),
    "IT Support Specialist": (
        "An IT Support Specialist provides direct technical assistance to end-users for hardware, software, and network issues. This role involves responding to support tickets, troubleshooting computers and peripherals, maintaining IT equipment, installing updates, managing user accounts, and documenting solutions. IT Support Specialists deliver training, conduct system checks, and work with vendors for repairs. Their goal is to ensure smooth IT operations, minimize downtime, and deliver outstanding customer support across various platforms and devices."
    ),
    "Systems Analyst": (
        "A Systems Analyst examines, designs, and implements IT systems to meet organizational needs. Responsibilities include analyzing business requirements, recommending process or technology improvements, creating technical documentation, and acting as a liaison between business and IT stakeholders. They coordinate development, testing, integration, upgrades, and ongoing maintenance of IT systems. The role involves ensuring solutions fulfill requirements, conducting systems and workflow analysis, supporting end-users, and maintaining compliance with policies and regulations."
    ),
    "Database Administrator": (
        "A Database Administrator (DBA) is responsible for the performance, security, and reliability of company databases such as MySQL, PostgreSQL, Oracle, or MongoDB. DBA duties include database installation, design, configuration, monitoring, optimization, backup and recovery, as well as managing user permissions. They troubleshoot errors, conduct performance tuning, document database environments, support developers with complex queries, and ensure data protection and compliance. DBAs plan for capacity and disaster recovery, and stay current with evolving database and security best practices."
    ),
    "DevOps Engineer": (
        "A DevOps Engineer streamlines the software development and deployment process by implementing automation, orchestration, and monitoring tools. They build and maintain robust CI/CD pipelines, manage infrastructure as code, and deploy containerized applications with Docker or Kubernetes. DevOps Engineers automate repetitive tasks, monitor system and application performance, enforce security measures, and support high availability and scalability. They work closely with development, QA, and operations teams to optimize delivery pipelines, reduce deployment risks, and foster a collaborative culture."
    ),
    "AI/Machine Learning Engineer": (
        "An AI/Machine Learning Engineer develops, deploys, and maintains machine learning and artificial intelligence solutions. Responsibilities include data preprocessing, feature engineering, selecting and tuning models, training and evaluating algorithms, and integrating models into production systems. They collaborate with data scientists and software engineers, monitor and retrain deployed models, and address issues related to monitoring, explainability, privacy, and fairness. The job involves using frameworks such as TensorFlow, PyTorch, Keras, and Scikit-learn, staying updated with advances in AI/ML, and contributing to innovation in data-driven decision-making."
    )
}
